name: Build

on:
  push:
  pull_request:

env:
  RAPIDWRIGHT_VERSION: v2020.2.6-beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Cache Jars & Data
        id: cache-rapidwright
        uses: actions/cache@v2
        with:
          path: |
              data
              jars
              bin
              build
          key: rapidwright-${{ env.RAPIDWRIGHT_VERSION }}
          restore-keys: |
            rapidwright-

      - name: Install RapidWright
        if: steps.cache-rapidwright.outputs.cache-hit != 'true'
        run: wget https://github.com/Xilinx/RapidWright/releases/download/${{ env.RAPIDWRIGHT_VERSION }}/rapidwright_jars.zip && unzip rapidwright_jars.zip && wget https://github.com/Xilinx/RapidWright/releases/download/${{ env.RAPIDWRIGHT_VERSION }}/rapidwright_data.zip && unzip rapidwright_data.zip
      - name: Compile & Test RapidWright
        run: ./gradlew build

